steps:
- name: "gcr.io/cloud-builders/mvn"
  entrypoint: "printenv"
  env: 
  -  "DATABASE_NAME=postgres"
  -  "JDBC_SCHEMA=userservice"
  -  "JDBC_USERNAME=postgres"
  secretEnv: 
  - "JDBC_URL"
  - "JDBC_PASSWORD"

secrets:
- kmsKeyName: "projects/project2-userteam/locations/global/keyRings/us-secrets/cryptoKeys/secrets-key"
  secretEnv:
    JDBC_URL: "CiQASM9lGlH2ciS2eFWdjtlZkEXBEydgZJZHgJAYGt0WGWrbEnISNgCmA8u6/pWVW26MMNravjZCETmhz95C0oMqQzfbbI8+vAH1Ycmq70oOivK1/EvLQv7so2FGJg=="
    JDBC_PASSWORD: "CiQASM9lGk1M9Mev92bPzTyEr1ul0iKLjesYNZhcJSwnJebD3gwSOgCmA8u62zVZcCET5oYB24orcn1mzJunkDIEmAvK68lEHb89a0QCedls+gIdNLt+C+xs5529UH/vTBo="
 
timeout: "1600s"
