steps:
- name: "gcr.io/cloud-builders/mvn"
  entrypoint: "mvn"
  args: ["package"]
  env: 
  -  "DATABASE_NAME=postgres"
  -  "JDBC_SCHEMA=userservice"
  -  "JDBC_USERNAME=postgres"
  secretEnv: 
  - "JDBC_URL"
  - "JDBC_PASSWORD"

- name: "gcr.io/cloud-builders/docker"
  entrypoint: "bash"
  args: ["-c", "docker build -t gcr.io/$PROJECT_ID/us-uat:latest --build-arg URL=$$JDBC_URL --build-arg PASSWORD=$$JDBC_PASSWORD ."]
  secretEnv: 
  - "JDBC_URL"
  - "JDBC_PASSWORD"

- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/us-uat:latest"]

- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy", "--image-url=gcr.io/$PROJECT_ID/us-uat:latest"]

secrets:
- kmsKeyName: "projects/project2-userteam/locations/global/keyRings/us-secrets/cryptoKeys/secrets-key"
  secretEnv:
    JDBC_URL: "CiQASM9lGkiEGk+n8zvvygOSOrWfJmufVRLP5rUpc26PSCMFUm4SNQCmA8u65oL5lKa+5opdqARqiKFu+n/40gM1K10Xtjgqv3YRUbusPmzW9AMp4o4MnbcGonFE"
    JDBC_PASSWORD: "CiQASM9lGtCbNGC/VmtR0izniRoI+LhWfEoKhE2OCwCANEloO1gSOQCmA8u6U7/aGFjcCavZ9OIz1Ef1dsbeXpYNazw2OLoWMbY9YGVEbKGSAmidnYUMkdevZ/C26xS3+g=="
 
timeout: "1600s"
