language: java
dist: trusty
sudo: enabled
jdk: oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - chmod +x mvnw
after_script:
  - docker build --build-arg db=$DATABASE_NAME,schema=$JDBC_SCHEMA,url=$JDBC_URL,username=$JDBC_USERNAME,password=$JDBC_PASSWORD
