language: java
dist: trusty
sudo: enabled
jdk: oraclejdk8
cache:
  directories:
  - $HOME/google-cloud-sdk
services:
  - docker
env:
  global:
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - chmod +x mvnw
  - chmod +x deploy.sh
  - openssl aes-256-cbc -K $encrypted_c52989533dfa_key -iv $encrypted_c52989533dfa_iv -in client-secret.json.enc -out client-secret.json -d
after_success:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then ./deploy.sh; fi
