language: java
dist: trusty
sudo: enabled
jdk: oraclejdk8
addons:
 postgresql: "9.6"
 apt:
   packages:
     - oracle-java8-installer
before_install:
- psql -c "create database db-production;" -U postgres
- sudo -u postgres psql -c "ALTER ROLE postgres WITH password 'postgres'"
- chmod +x mvnw
services:
- postgresql
