language: java
sudo: true
dist: trusty
#trusty may be the incorrect distro. Check this if there are problems
jdk: openjdk8
addons:
 apt:
   packages:
     - open-java8-installer
before_install:
 - chmod +x mvnw
