apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: user-service
spec:
  revisionHistoryLimit: 1
  replicas: 1
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: gcr.io/project2-userteam/user-service:v1
        env:
          - name: POSTGRES_DB_HOST
            value: 10.96.64.4
          - name: POSTGRES_DB_USER
            value: posgres
          - name: POSTGRES_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-pass
                key: password
          - name: JDBC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-pass
                key: password
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
        resources:
          limits:
            cpu: 70m
          requests:
            cpu: 70m
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: user-service
